WINDOW_TITLE = 'Cube detector'

FILTER_MIN_BRIGHTNESS = 100
FILTER_ADD_BRIGHTNESS = 255

DETECTION_CLUSTER_SIZE = 3 # It is limited to solving 3x3 cubes for now
DETECTION_MIN_AREA = 400
DETECTION_MIN_DISTANCE_BETWEEN_CENTERS = 30

GRAPHICS_OFFSET_CUBEFACE = 10
GRAPHICS_SIZE_CUBEFACE   = 25